import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import usersRouter from "./users.js";
import postsRouter from "./posts.js";
import pollsRouter from "./polls.js";
import servicesRouter from "./services.js";
import statsRouter from "./stats.js";
import notificationsRouter from "./notifications.js";
import schoolVotesRouter from "./school-votes.js";
import storageRouter from "./storage.js";
import adminRouter from "./admin.js";
import messagesRouter from "./messages.js";
import paymentsRouter from "./payments.js";
import reportsRouter from "./reports.js";
import shuttleStatusRouter from "./shuttle-status.js";
import cgpaPlanRouter from "./cgpa-plan.js";
import wazobiaRouter from "./wazobia.js";
import matricClaimsRouter from "./matric-claims.js";
import adsRouter from "./ads.js";

const router = Router() as any;

router.use(healthRouter);
router.use(usersRouter);
router.use(postsRouter);
router.use(pollsRouter);
router.use(servicesRouter);
router.use(statsRouter);
router.use(notificationsRouter);
router.use(schoolVotesRouter);
router.use(storageRouter);
router.use(adminRouter);
router.use(messagesRouter);
router.use(paymentsRouter);
router.use(reportsRouter);
router.use(shuttleStatusRouter);
router.use(cgpaPlanRouter);
router.use(wazobiaRouter);
router.use(matricClaimsRouter);
router.use(adsRouter);

export default router;
