kind = "web"
previewPath = "/"
title = "CampusX"
version = "1.0.0"
id = "artifacts/campusx"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26234

[services.development]
run = "pnpm --filter @workspace/campusx run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/campusx", "run", "build" ]
publicDir = "artifacts/campusx/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26234"
BASE_PATH = "/"
